### PR TITLE
Update our Dockerfile from the official Odoo 14 one

### PR DESCRIPTION
**Pull request by Nick-OpusVL**
https://github.com/odoo/docker/blob/563544203e98e234b52ce19bb3c6357fca6b2c98/14.0/Dockerfile

Can reviewers please proof-read.  I'm especially interested to know
* whether I should be updating the wkhtmltox version;
* whether to copy in the CMD ["odoo"] line; and
* whether to keep xlrd (as it wasn't listed in the new version but some of our stuff might need it)

### CODE REVIEW

**Comment by DaeronAlagos** [comment]
Don't update the wkhtmltox version. I've tried that before and started getting weird results. It's mostly down to how html5/css/bootstrap plays nicely with wkhtmltox. I've used other versions on personal projects and get different results every time.

**Comment by DaeronAlagos** [comment]
I'm not sure if the CMD line is needed. Depends on how the entrypoint is constructed.

**Comment by DaeronAlagos** [comment]
I think xlrd is an old xslx parser. I've been using xslwriter in 13.0 and that works fine. If we are porting something from say 8.0 to 14.0 then so much would have to change anyway it's not much more to have to change xlrd to xslwriter.

**Comment by Nick-OpusVL** [comment]
> I'm not sure if the CMD line is needed. Depends on how the entrypoint is constructed.

I'll check whether it's a new addition between official v13 and official v14.  If it's not, I'll take it out.

**Comment by Nick-OpusVL** [comment]
> I think xlrd is an old xslx parser. I've been using xslwriter in 13.0 and that works fine. If we are porting something from say 8.0 to 14.0 then so much would have to change anyway it's not much more to have to change xlrd to xslwriter.

Does that mean xlswriter has a (decent) parser built in too?

**Comment by Nick-OpusVL** [comment]
> Don't update the wkhtmltox version. I've tried that before and started getting weird results. It's mostly down to how html5/css/bootstrap plays nicely with wkhtmltox. I've used other versions on personal projects and get different results every time.

OK I'll revert that

**Comment by Nick-OpusVL** [comment]
> > I'm not sure if the CMD line is needed. Depends on how the entrypoint is constructed.
> 
> I'll check whether it's a new addition between official v13 and official v14. If it's not, I'll take it out.

I've just compared https://github.com/odoo/docker/blob/563544203e98e234b52ce19bb3c6357fca6b2c98/13.0/Dockerfile with https://github.com/odoo/docker/blob/563544203e98e234b52ce19bb3c6357fca6b2c98/14.0/Dockerfile and the 'CMD' line is the same on both.
Therefore it's not a new entrypoint requirement for 14.

It wasn't in our previous (v13) Dockerfile
So I'm going to remove it from our v14 Dockerfile too.

**Comment by DaeronAlagos** [comment]
> > I think xlrd is an old xslx parser. I've been using xslwriter in 13.0 and that works fine. If we are porting something from say 8.0 to 14.0 then so much would have to change anyway it's not much more to have to change xlrd to xslwriter.
> 
> Does that mean xlswriter has a (decent) parser built in too?

@Nick-OpusVL The latest incarnation of an importer inherits from base_import module so we can lean on all that's built in parsing of different file types. Is working well so far :)

**Comment by Nick-OpusVL** [comment]
> > > I think xlrd is an old xslx parser. I've been using xslwriter in 13.0 and that works fine. If we are porting something from say 8.0 to 14.0 then so much would have to change anyway it's not much more to have to change xlrd to xslwriter.
> > 
> > 
> > Does that mean xlswriter has a (decent) parser built in too?
> 
> @Nick-OpusVL The latest incarnation of an importer inherits from base_import module so we can lean on all that's built in parsing of different file types. Is working well so far :)

OK I'll remove xlrd then

**Comment by Nick-OpusVL** [comment]
> > > > I think xlrd is an old xslx parser. I've been using xslwriter in 13.0 and that works fine. If we are porting something from say 8.0 to 14.0 then so much would have to change anyway it's not much more to have to change xlrd to xslwriter.
> > > 
> > > 
> > > Does that mean xlswriter has a (decent) parser built in too?
> > 
> > 
> > @Nick-OpusVL The latest incarnation of an importer inherits from base_import module so we can lean on all that's built in parsing of different file types. Is working well so far :)
> 
> OK I'll remove xlrd then

I think I got confused somewhere down the line - it looks like 14.0/Dockerfile installs both python3-xlrd and python3-xlwt, so I actually need to put xlrd in.  I must have misinterpreted the vimdiff output.

**Comment by Nick-OpusVL** [comment]
@DaeronAlagos I think this is ready for you to re-review now.  Pay attention to comments on the PR.

**Review by DaeronAlagos — APPROVED** [review]
Noticed that they've switched to apt for install the .deb I did wonder why they'd done it like that historically.

**Comment by Nick-OpusVL** [comment]
> Noticed that they've switched to apt for install the .deb I did wonder why they'd done it like that historically.

Maybe (and this is just an educated guess) previous versions of apt-get didn't support installing from a file.  I recall installing and using gdebi to install a file along with its dependencies previously.  I hope I wasn't doing that unnecessarily with APT able to do it all along.

**Pull request merged**
